version: 0.2
proxy:
  upload-artifacts: yes
  logs: yes
phases:
  install:
    commands:
      - apt-get install wget unzip
      - wget -q https://releases.hashicorp.com/terraform/0.12.10/terraform_0.12.10_linux_amd64.zip -O terraform.zip
      - unzip ./terraform.zip -d /usr/local/bin/
  build:
    commands:
      - env
      - aws s3 ls
      - TF_LOG=debug terraform init
      - TF_LOG=debug terraform workspace select $STAGE
      - TF_LOG=debug terraform validate 
      - TF_LOG=debug terraform plan -var-file="variables/$STAGE.tfvars" -out="tfplan"
      - TF_LOG=debug terraform apply "tfplan"
artifacts:
  files:
    -  tfplan