version: 0.2
proxy:
  upload-artifacts: yes
  logs: yes
phases:
  install:
    commands:
      - apt-get install wget unzip jq
      - wget -q https://releases.hashicorp.com/terraform/0.12.10/terraform_0.12.10_linux_amd64.zip -O terraform.zip
      - unzip ./terraform.zip -d /usr/local/bin/
  build:
    commands:
      - env
      - aws s3 ls --debug
      - curl -o security-credentials.json http://169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
      - cat security-credentials.json
      - export AWS_ACCESS_KEY_ID=$(cat security-credentials.json | jq -r '.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(cat security-credentials.json | jq -r '.SecretAccessKey')
      - export AWS_SECURITY_TOKEN=$(cat security-credentials.json | jq -r '.Token')
      - mkdir $HOME/.aws
      - echo '[default]' > $HOME/.aws/credentials
      - echo aws_access_key_id=$AWS_ACCESS_KEY_ID >> $HOME/.aws/credentials
      - echo aws_secret_access_key=$AWS_SECRET_ACCESS_KEY >> $HOME/.aws/credentials
      - echo aws_session_token=$AWS_SECURITY_TOKEN >> $HOME/.aws/credentials
      - echo region=us-east-1 >> $HOME/.aws/credentials
      - cat .aws/credentials
      - echo '[default]' > $HOME/.aws/config
      - echo aws_access_key_id=$AWS_ACCESS_KEY_ID >> $HOME/.aws/config
      - echo aws_secret_access_key=$AWS_SECRET_ACCESS_KEY >> $HOME/.aws/config
      - echo aws_session_token=$AWS_SECURITY_TOKEN >> $HOME/.aws/config
      - echo region=us-east-1 >> $HOME/.aws/config
      - aws s3 ls --profile default --debug
      #- curl -x $https_proxy 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI 
      - TF_LOG=debug terraform init
      - TF_LOG=debug terraform workspace select $STAGE
      - TF_LOG=debug terraform validate 
      - TF_LOG=debug terraform plan -var-file="variables/$STAGE.tfvars" -out="tfplan"
      - TF_LOG=debug terraform apply "tfplan"
artifacts:
  files:
    -  tfplan