version: 0.2
#proxy:
#  upload-artifacts: yes
#  logs: yes
phases:
  install:
    commands:
      - apt-get install wget unzip
      - wget -q https://releases.hashicorp.com/terraform/0.12.10/terraform_0.12.10_linux_amd64.zip -O terraform.zip
      - unzip ./terraform.zip -d /usr/local/bin/
  build:
    commands:
      - docker run -e AWS_DEFAULT_REGION -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI aws/codebuild/standard:1.0
      - terraform init
      - terraform workspace select $STAGE
      - terraform validate 
      - terraform plan -var-file="variables/$STAGE.tfvars" -out="tfplan"
      - terraform apply "tfplan"
artifacts:
  files:
    -  tfplan